name: ShadovStatus
description:
version: 1.0
api-version: 1.16
main: filip.filipeex.karab.Main
depend:
  - PlaceholderAPI


commands:
  shadovstatus:
    usage: /<command> <server|reload> [status]
    description: Sets the status of a server.


permissions:
  shadovstatus.admin:
    default: op
    description: Allows the holder to use the /shadovstatus command, therefore change the statuses of any server.